### ISSUE TITLE
Failed to generate video

### ISSUE THREAD

**Issue by zeevblu** [imgly/vesdk-ios-build#1]
When set the "configureVideoEditViewController" with "forceCropMode = true" 
and set the "configureTransformToolController" with "allowFreeCrop = false" and 
                "transformBuilder.allowedCropRatios = [.init(width: 9, height: 16)]" only.

The editor failed to generate the video and call to "videoEditViewControllerDidFailToGenerateVideo"

**Comment by sascha** [comment]
Hi @zeevblu, if this is still an issue with the latest version of the SDK, please reach out via https://support.videoeditorsdk.com.
