### ISSUE TITLE
Crashing when open VideoEditViewController

### ISSUE THREAD

**Issue by hitendigi** [imgly/vesdk-ios-build#2]
The sample app is also crashing when open Editor.
Check Below screenshot
I Did nothing just pod install and run sample example in swift.
<img width="1148" alt="Screenshot 2020-09-23 at 3 29 37 PM" src="https://user-images.githubusercontent.com/49969242/93998304-f9c99d80-fdb1-11ea-98d0-0698e607cdef.png">

I have tried with adding a license also, but it is still crashing.

**Comment by 018arpitjain018** [comment]
@hitendigi I'm also facing the same issue, did you able to fix this??

**Comment by sascha** [comment]
Hi folks, please reach out via https://support.videoeditorsdk.com if this still is an issue with the latest version.
