### ISSUE TITLE
Video Editor SDK compile issue in iOS

### ISSUE THREAD

**Issue by dhruv-dhola** [imgly/vesdk-ios-build#3]
in Xcode version 12 I got an error in compile time like this:-
"Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler"

**Comment by sehosseini** [comment]
I have the same problem. And I need to use the Xcode 12

**Comment by sascha** [comment]
Hi @dhruv-dhola,
this should be fixed with the latest versions of the SDK. In the future, please reach out via https://support.videoeditorsdk.com.
