### ISSUE TITLE
Memory Leak While unlocking License

### ISSUE THREAD

**Issue by gauravgargretailogy** [imgly/vesdk-ios-build#4]
When unlocking with my license key the instrument is showing the leak. You can see in the attached screenshot.

`VESDK.unlockWithLicense(at: licenseURL)`

<img width="1434" alt="Screenshot 2020-11-02 at 6 45 25 PM" src="https://user-images.githubusercontent.com/72732356/97872459-13102300-1d3c-11eb-9bd1-1f41368ebe48.png">

**Comment by sascha** [comment]
Hi @gauravgargretailogy, if this is still an issue with the latest version of the SDK, please reach out via https://support.videoeditorsdk.com.
